/*
* System......... Graphics Interface Library for Clipper 
* Program I.D.... GrfxText.H
* Description.... Header file for gDrawText() Function 
*                  
* Author......... jay ocampo
* Date Started... June 1994
*/



/* Defined Constants for gDrawText WrapFlag parameter */
#define WRAPTEXT_OFF     0              /* Truncates text output after window border */
#define WRAPTEXT_ON      1              /* Wraps text to next line after window border */


/* Defined Constants for gDrawText UlineFlag parameter */
#define ULINE_OFF        0              /* Normal Text display */
#define ULINE_ON         1              /* Underline Text      */

